export const TIERS = [
  { id: "T1", label: "T1", fullLabel: "Direct Threats", color: "#dc2626", bg: "#fee2e2" },
  { id: "T2", label: "T2", fullLabel: "Adjacent Players", color: "#ea580c", bg: "#ffedd5" },
  { id: "T3", label: "T3", fullLabel: "Emerging", color: "#6366f1", bg: "#eef2ff" },
];

export const COMPETITORS = [
  { id: "powerbi", name: "Microsoft Power BI", short: "Power BI", color: "#eab308", tier: "T1" },
  { id: "snowflake", name: "Snowflake Intelligence", short: "Snowflake", color: "#29B5E8", tier: "T1" },
  { id: "databricks", name: "Databricks Genie", short: "Databricks", color: "#FF3621", tier: "T1" },
  { id: "sigma", name: "Sigma Computing", short: "Sigma", color: "#6C5CE7", tier: "T2" },
  { id: "hex", name: "HEX", short: "HEX", color: "#E84393", tier: "T2" },
  { id: "tableau", name: "Tableau Einstein", short: "Tableau", color: "#E97627", tier: "T2" },
  { id: "omni", name: "Omni", short: "Omni", color: "#00B894", tier: "T3" },
];

export const PERSONAS = [
  { id: "data-analyst", label: "Data Analyst" },
  { id: "data-engineer", label: "Data Engineer" },
  { id: "business-user", label: "Business User" },
  { id: "cdo", label: "CDO / Data Leader" },
  { id: "developer", label: "Developer / Data Scientist" },
];

export const INDUSTRIES = [
  { id: "financial", label: "Financial Services" },
  { id: "healthcare", label: "Healthcare" },
  { id: "retail", label: "Retail & E-Commerce" },
  { id: "tech", label: "Technology / SaaS" },
  { id: "manufacturing", label: "Manufacturing" },
];

export const CHALLENGES = [
  { id: "slow-insights", label: "Slow Time-to-Insight" },
  { id: "data-silos", label: "Data Silos & Fragmentation" },
  { id: "lack-self-service", label: "Lack of Self-Service" },
  { id: "inconsistent-metrics", label: "Inconsistent Metrics" },
  { id: "compliance-risk", label: "Compliance & Security Risk" },
  { id: "collaboration-gaps", label: "Collaboration Gaps" },
  { id: "alert-fatigue", label: "Missed Anomalies" },
  { id: "dashboard-bottleneck", label: "Dashboard Bottleneck" },
  { id: "vendor-lock-in", label: "Vendor Lock-In" },
  { id: "technical-barrier", label: "Technical Skill Barrier" },
];

export const OUTCOME_CATEGORIES = [
  { id: "decision-velocity", label: "Decision Velocity" },
  { id: "operational-efficiency", label: "Operational Efficiency" },
  { id: "trust-governance", label: "Trust & Governance" },
];

export const KEY_METRICS = [
  { id: "mtti", label: "MTTI (Mean Time to Insight)" },
  { id: "etl-cost-analyst-leverage", label: "ETL Cost Reduction / Analyst Leverage Ratio" },
  { id: "query-accuracy-adoption", label: "Query Accuracy % / Active Non-Technical Users" },
];

export const USE_CASES = [
  {
    id: "uc-01",
    title: "Ask follow-up questions in plain English without rewriting SQL",
    persona: "data-analyst",
    industries: ["financial", "retail", "tech", "healthcare", "manufacturing"],
    challenge: "slow-insights",
    outcomeCategory: "decision-velocity",
    keyMetric: "mtti",
    relatedProduct: "WisdomAI Core",
    features: ["Natural Language to SQL", "Conversational Context / Multi-Turn"],
    expectedOutcome: "Analysts iterate 10x faster on complex queries through multi-turn conversation",
    before: { label: "Query iteration cycle", value: "15-30 min per revision" },
    after: { label: "Query iteration cycle", value: "< 30 sec follow-up" },
    scores: { wisdomai: 5, snowflake: 3, databricks: 4, powerbi: 3, sigma: 3, omni: 3, hex: 4, tableau: 3 },
    notes: {
      wisdomai: "Full multi-turn context: AI remembers prior queries, filters, and assumptions across an entire session.",
      snowflake: "Cortex Analyst is stateless — each question starts from scratch with no context memory.",
      databricks: "Genie supports NL-to-SQL but has limited context window on follow-up questions.",
      powerbi: "Copilot handles DAX but not full SQL; follow-up context is session-limited.",
      sigma: "AI Assist helps with formulas, not full conversational querying.",
      omni: "Basic NL interface; no multi-turn conversation support.",
      hex: "Magic AI generates SQL/Python well but context retention is notebook-scoped.",
      tableau: "Tableau Einstein AI generates SQL from NL but conversation context is limited to single queries.",
    },
  },
  {
    id: "uc-02",
    title: "Auto-generate the right chart type from any query result",
    persona: "data-analyst",
    industries: ["retail", "tech", "financial"],
    challenge: "dashboard-bottleneck",
    outcomeCategory: "decision-velocity",
    keyMetric: "mtti",
    relatedProduct: "WisdomAI Dashboards",
    features: ["Auto-Visualization Generation", "Built-in Chart Types & Library"],
    expectedOutcome: "Dashboards created in minutes instead of days with AI-recommended visualizations",
    before: { label: "Dashboard build time", value: "2-5 days" },
    after: { label: "Dashboard build time", value: "< 1 hour" },
    scores: { wisdomai: 5, snowflake: 2, databricks: 3, powerbi: 5, sigma: 4, omni: 4, hex: 4, tableau: 5 },
    notes: {
      wisdomai: "AI analyzes data shape, cardinality, and context to auto-select and generate optimal chart type.",
      snowflake: "Minimal native visualization — relies on partner BI tools.",
      databricks: "Notebook charts are basic; dashboard capabilities are limited.",
      powerbi: "Excellent chart library and auto-recommendations; industry-leading viz.",
      sigma: "Strong chart options with spreadsheet-like flexibility.",
      omni: "Good auto-viz with clean modern UI.",
      hex: "Beautiful chart rendering; notebook-first but strong visualization library.",
      tableau: "Tableau Einstein AI generates SQL from NL but conversation context is limited to single queries.",
    },
  },
  {
    id: "uc-03",
    title: "Collaborate on a shared analysis in real-time with teammates",
    persona: "data-analyst",
    industries: ["tech", "financial", "retail"],
    challenge: "collaboration-gaps",
    outcomeCategory: "operational-efficiency",
    keyMetric: "etl-cost-analyst-leverage",
    relatedProduct: "WisdomAI Workspaces",
    features: ["Real-Time Multi-User Editing", "Comments & Annotations", "Version Control & History"],
    expectedOutcome: "Teams co-create analyses simultaneously, eliminating version conflicts and duplication",
    before: { label: "Analysis duplication", value: "~35% redundant work" },
    after: { label: "Analysis duplication", value: "< 5%" },
    scores: { wisdomai: 5, snowflake: 2, databricks: 3, powerbi: 3, sigma: 5, omni: 3, hex: 5, tableau: 3 },
    notes: {
      wisdomai: "Google Docs-style real-time multiplayer with AI assistance embedded in the workspace.",
      snowflake: "Single-user worksheet model; no collaborative editing.",
      databricks: "Notebook sharing exists but not real-time co-editing; Git-based workflow.",
      powerbi: "Shared workspaces available but no real-time concurrent editing.",
      sigma: "Excellent real-time multiplayer editing — strong competitor here.",
      omni: "Basic sharing and collaboration; no real-time co-editing.",
      hex: "Strong multiplayer notebooks; closest to true collaborative analytics.",
      tableau: "Tableau Cloud collaboration exists but no real-time co-editing of workbooks.",
    },
  },
  {
    id: "uc-04",
    title: "Answer my own data questions without filing a ticket to the data team",
    persona: "business-user",
    industries: ["retail", "healthcare", "manufacturing", "financial"],
    challenge: "lack-self-service",
    outcomeCategory: "trust-governance",
    keyMetric: "query-accuracy-adoption",
    relatedProduct: "WisdomAI Explorer",
    features: ["No-Code Data Exploration", "Ad-Hoc Query Builder", "Natural Language to SQL"],
    expectedOutcome: "Business users self-serve 80% of routine data questions directly",
    before: { label: "Self-service adoption", value: "~20% of business users" },
    after: { label: "Self-service adoption", value: "> 75%" },
    scores: { wisdomai: 5, snowflake: 2, databricks: 2, powerbi: 5, sigma: 5, omni: 4, hex: 2, tableau: 4 },
    notes: {
      wisdomai: "Conversational AI + no-code UI means any business user can ask questions in plain English.",
      snowflake: "Technical SQL interface; not designed for business user self-service.",
      databricks: "Notebook-first approach; steep learning curve for non-technical users.",
      powerbi: "Mature drag-and-drop self-service; industry-leading for business users.",
      sigma: "Spreadsheet-like interface makes analytics accessible to Excel-native users.",
      omni: "Good exploration tools but slightly more technical than Power BI/Sigma.",
      hex: "Code-first environment; excellent for technical users, challenging for business users.",
      tableau: "Tableau Einstein AI generates SQL from NL but conversation context is limited to single queries.",
    },
  },
  {
    id: "uc-05",
    title: "Get a weekly AI-generated summary of my KPIs and what changed",
    persona: "business-user",
    industries: ["retail", "financial", "tech"],
    challenge: "alert-fatigue",
    outcomeCategory: "decision-velocity",
    keyMetric: "mtti",
    relatedProduct: "WisdomAI Insights",
    features: ["AI-Generated Insights & Summaries", "Scheduled Report Delivery", "Slack / Teams Integration"],
    expectedOutcome: "Executives receive actionable AI summaries instead of static PDF reports",
    before: { label: "Report consumption", value: "Manual review, often skipped" },
    after: { label: "Report consumption", value: "AI digest in Slack/email" },
    scores: { wisdomai: 5, snowflake: 2, databricks: 2, powerbi: 3, sigma: 3, omni: 2, hex: 3, tableau: 3 },
    notes: {
      wisdomai: "AI automatically generates narrative summaries with anomaly callouts delivered on schedule.",
      snowflake: "No native scheduled insight delivery; requires external orchestration.",
      databricks: "Can build custom alert notebooks but no built-in summary generation.",
      powerbi: "Smart Narratives exists but is surface-level; scheduled delivery is email-only.",
      sigma: "Scheduled report delivery exists; no AI-generated narrative summaries.",
      omni: "Basic scheduled delivery; no AI summarization capability.",
      hex: "Scheduled notebooks possible; AI can assist but no built-in digest feature.",
      tableau: "Tableau Pulse provides AI-driven metric summaries; still maturing.",
    },
  },
  {
    id: "uc-06",
    title: "Drill into a dashboard number to understand why it changed",
    persona: "business-user",
    industries: ["retail", "financial", "healthcare", "manufacturing"],
    challenge: "slow-insights",
    outcomeCategory: "decision-velocity",
    keyMetric: "mtti",
    relatedProduct: "WisdomAI Dashboards",
    features: ["Drill-Down & Cross-Filtering", "Interactive Dashboard Design", "AI-Generated Insights & Summaries"],
    expectedOutcome: "Users go from 'what happened' to 'why it happened' in seconds with AI-guided drill-down",
    before: { label: "Root cause time", value: "Hours (manual investigation)" },
    after: { label: "Root cause time", value: "Seconds (AI-guided drill)" },
    scores: { wisdomai: 5, snowflake: 2, databricks: 2, powerbi: 4, sigma: 4, omni: 4, hex: 3, tableau: 4 },
    notes: {
      wisdomai: "AI explains WHY a metric changed, not just what changed — proactive root cause analysis.",
      snowflake: "No native dashboard drill-down; relies on partner tools.",
      databricks: "Notebook-based; drill-down requires manual query modification.",
      powerbi: "Strong cross-filtering and drill-down capabilities built-in.",
      sigma: "Good interactive drill-down with spreadsheet-style exploration.",
      omni: "Solid drill-down and cross-filtering in dashboards.",
      hex: "Limited dashboard interactivity; exploration is notebook-based.",
      tableau: "Excellent drill-down and cross-filtering; Explain Data feature for root cause.",
    },
  },
  {
    id: "uc-07",
    title: "Enforce a single source of truth for metrics across all teams",
    persona: "cdo",
    industries: ["financial", "healthcare", "manufacturing"],
    challenge: "inconsistent-metrics",
    outcomeCategory: "trust-governance",
    keyMetric: "query-accuracy-adoption",
    relatedProduct: "WisdomAI Semantic Layer",
    features: ["Governed Semantic Layer", "Metric Store / Definitions", "Data Lineage & Impact Analysis"],
    expectedOutcome: "Every team uses the same governed metric definitions — no more 'my numbers don't match yours'",
    before: { label: "Metric consistency", value: "~60% cross-team agreement" },
    after: { label: "Metric consistency", value: "100% governed definitions" },
    scores: { wisdomai: 5, snowflake: 3, databricks: 4, powerbi: 4, sigma: 4, omni: 5, hex: 3, tableau: 4 },
    notes: {
      wisdomai: "Unified semantic layer accessible across all AI modes, queries, and dashboards.",
      snowflake: "Relies on partner semantic layers (dbt, AtScale); no native unified governance.",
      databricks: "Unity Catalog strong for data governance; dedicated metric layer still maturing.",
      powerbi: "Power BI semantic model is mature but tightly coupled to Microsoft stack.",
      sigma: "Strong governed metrics within Sigma; limited reach outside the tool.",
      omni: "Excellent shared modeling layer — strongest competitor on metric governance.",
      hex: "Minimal governance tooling; depends on external metric stores.",
      tableau: "Tableau Catalog and metrics layer provide governance; Salesforce ecosystem-coupled.",
    },
  },
  {
    id: "uc-08",
    title: "Detect revenue anomalies and market shifts before they hit the P&L",
    persona: "cdo",
    industries: ["financial", "retail", "tech"],
    challenge: "alert-fatigue",
    outcomeCategory: "decision-velocity",
    keyMetric: "mtti",
    relatedProduct: "WisdomAI Insights",
    features: ["AI-Generated Insights & Summaries", "Semantic Model / Business Logic Layer"],
    expectedOutcome: "AI surfaces business-critical anomalies proactively without anyone needing to ask",
    before: { label: "Anomaly detection", value: "Days to weeks (manual)" },
    after: { label: "Anomaly detection", value: "Real-time, AI-driven" },
    scores: { wisdomai: 5, snowflake: 2, databricks: 3, powerbi: 3, sigma: 2, omni: 2, hex: 3, tableau: 3 },
    notes: {
      wisdomai: "Purpose-built proactive intelligence: AI continuously monitors business metrics and flags anomalies.",
      snowflake: "No proactive insight generation — purely responsive to explicit user queries.",
      databricks: "Can build anomaly detection in notebooks but requires manual setup and maintenance.",
      powerbi: "Quick Insights exist but limited depth; no continuous monitoring engine.",
      sigma: "No proactive insights — users must build alert rules manually.",
      omni: "No automated insight surfacing capability.",
      hex: "Notebooks can run scheduled anomaly detection but no native proactive engine.",
      tableau: "Tableau Pulse surfaces some anomalies; not a continuous proactive engine.",
    },
  },
  {
    id: "uc-09",
    title: "Pass SOC 2 / HIPAA audit without a month of preparation",
    persona: "cdo",
    industries: ["financial", "healthcare"],
    challenge: "compliance-risk",
    outcomeCategory: "trust-governance",
    keyMetric: "query-accuracy-adoption",
    relatedProduct: "WisdomAI Enterprise",
    features: ["Audit Trails & Compliance", "SSO / SAML / SCIM", "Data Classification & Sensitivity", "Row-Level Security (RLS)"],
    expectedOutcome: "Automated audit trails and data classification reduce compliance prep from weeks to days",
    before: { label: "Audit prep time", value: "3-6 weeks manual work" },
    after: { label: "Audit prep time", value: "Automated, always-on" },
    scores: { wisdomai: 4, snowflake: 5, databricks: 5, powerbi: 5, sigma: 4, omni: 3, hex: 3, tableau: 4 },
    notes: {
      wisdomai: "Comprehensive audit trails, SSO/SCIM, row-level security, and data classification built-in.",
      snowflake: "Enterprise-grade: SOC 2 Type II, HIPAA, FedRAMP certified. Very mature.",
      databricks: "Strong enterprise security via Unity Catalog; fine-grained access control.",
      powerbi: "Deep Azure AD integration; inherits Microsoft's extensive compliance certifications.",
      sigma: "SOC 2 certified with good enterprise features; compliance portfolio growing.",
      omni: "Adequate for mid-market; advanced enterprise governance still maturing.",
      hex: "SOC 2 certified but limited advanced governance and compliance features.",
      tableau: "Salesforce-grade security; SOC 2, HIPAA support via Salesforce Shield.",
    },
  },
  {
    id: "uc-10",
    title: "Query across Snowflake, BigQuery, and Redshift without building ETL pipelines",
    persona: "data-engineer",
    industries: ["tech", "financial", "manufacturing", "retail"],
    challenge: "data-silos",
    outcomeCategory: "operational-efficiency",
    keyMetric: "etl-cost-analyst-leverage",
    relatedProduct: "WisdomAI Connect",
    features: ["Cloud Data Warehouse Support", "Live Data / Direct Query", "Third-Party Data Source Connectors"],
    expectedOutcome: "Unified query layer across all warehouses eliminates vendor lock-in and ETL overhead",
    before: { label: "Cross-warehouse setup", value: "Days of ETL pipeline work" },
    after: { label: "Cross-warehouse setup", value: "Minutes with federation" },
    scores: { wisdomai: 4, snowflake: 3, databricks: 4, powerbi: 5, sigma: 5, omni: 5, hex: 3, tableau: 4 },
    notes: {
      wisdomai: "Multi-warehouse connectivity with unified query layer — no lock-in.",
      snowflake: "Snowflake-native only; deep integration but hard platform lock-in.",
      databricks: "Strong within Databricks ecosystem; multi-cloud support growing.",
      powerbi: "300+ connectors — broadest connectivity but Microsoft-centric governance.",
      sigma: "Native support for Snowflake, BigQuery, Redshift, Databricks.",
      omni: "Strong multi-source support with unified modeling layer.",
      hex: "Snowflake, BigQuery, Redshift primary; limited connector breadth.",
      tableau: "Broad connector library; supports many data sources natively.",
    },
  },
  {
    id: "uc-11",
    title: "Integrate dbt models directly into the analytics layer",
    persona: "data-engineer",
    industries: ["tech", "financial"],
    challenge: "data-silos",
    outcomeCategory: "operational-efficiency",
    keyMetric: "etl-cost-analyst-leverage",
    relatedProduct: "WisdomAI Connect",
    features: ["dbt / Transformation Integration", "Governed Semantic Layer"],
    expectedOutcome: "dbt models flow directly into governed analytics — no translation layer needed",
    before: { label: "Model-to-analytics gap", value: "Manual sync, often stale" },
    after: { label: "Model-to-analytics gap", value: "Native integration, always current" },
    scores: { wisdomai: 4, snowflake: 3, databricks: 4, powerbi: 3, sigma: 4, omni: 5, hex: 4, tableau: 3 },
    notes: {
      wisdomai: "Native dbt integration with semantic layer pass-through.",
      snowflake: "dbt runs on Snowflake but semantic layer is external.",
      databricks: "Growing dbt integration; Unity Catalog provides governance.",
      powerbi: "Limited dbt awareness; separate semantic model.",
      sigma: "Good dbt integration; metrics flow into Sigma models.",
      omni: "Excellent dbt-native modeling — best-in-class integration.",
      hex: "dbt integration via connections; notebook-based exploration on top.",
      tableau: "Basic dbt awareness; semantic layer integration still developing.",
    },
  },
  {
    id: "uc-12",
    title: "Track data lineage to understand the impact of schema changes",
    persona: "data-engineer",
    industries: ["financial", "healthcare", "manufacturing"],
    challenge: "compliance-risk",
    outcomeCategory: "trust-governance",
    keyMetric: "query-accuracy-adoption",
    relatedProduct: "WisdomAI Semantic Layer",
    features: ["Data Lineage & Impact Analysis", "Data Classification & Sensitivity"],
    expectedOutcome: "See exactly which dashboards and metrics break before making any schema change",
    before: { label: "Impact analysis", value: "Manual, incomplete" },
    after: { label: "Impact analysis", value: "Automated dependency graph" },
    scores: { wisdomai: 4, snowflake: 4, databricks: 5, powerbi: 4, sigma: 3, omni: 4, hex: 3, tableau: 4 },
    notes: {
      wisdomai: "Built-in lineage tracking from source through semantic layer to dashboard.",
      snowflake: "Snowflake Horizon provides object-level lineage within the platform.",
      databricks: "Unity Catalog offers the most comprehensive lineage and impact analysis.",
      powerbi: "Lineage within Power BI ecosystem; limited outside Microsoft tools.",
      sigma: "Basic lineage within Sigma; no cross-platform dependency tracking.",
      omni: "Good lineage tracking within the modeling layer.",
      hex: "Minimal lineage tooling; notebook-level dependencies only.",
      tableau: "Tableau Catalog provides lineage within the Tableau ecosystem.",
    },
  },
  {
    id: "uc-13",
    title: "Generate SQL, Python, or R code from a natural language description",
    persona: "developer",
    industries: ["tech", "financial", "retail"],
    challenge: "slow-insights",
    outcomeCategory: "operational-efficiency",
    keyMetric: "etl-cost-analyst-leverage",
    relatedProduct: "WisdomAI Core",
    features: ["Code Generation (SQL/Python/R)", "Natural Language to SQL"],
    expectedOutcome: "Data scientists prototype analyses 5x faster with AI code generation",
    before: { label: "Code prototyping", value: "30-60 min per analysis" },
    after: { label: "Code prototyping", value: "< 5 min with AI assist" },
    scores: { wisdomai: 4, snowflake: 3, databricks: 4, powerbi: 2, sigma: 3, omni: 3, hex: 5, tableau: 3 },
    notes: {
      wisdomai: "Multi-language code generation grounded in semantic layer for accuracy.",
      snowflake: "Cortex generates SQL only; no Python/R code generation.",
      databricks: "Databricks Assistant generates SQL and Python within notebooks.",
      powerbi: "Limited to DAX and M formula generation; no general code gen.",
      sigma: "AI Assist for Sigma formulas; not general-purpose code generation.",
      omni: "Basic SQL generation; no Python/R support.",
      hex: "Magic AI is best-in-class for SQL + Python generation in notebook context.",
      tableau: "Einstein AI generates calculations; no Python/R code generation.",
    },
  },
  {
    id: "uc-14",
    title: "Embed analytics into our customer-facing SaaS product",
    persona: "developer",
    industries: ["tech"],
    challenge: "dashboard-bottleneck",
    outcomeCategory: "operational-efficiency",
    keyMetric: "etl-cost-analyst-leverage",
    relatedProduct: "WisdomAI Platform",
    features: ["Embedded Analytics", "API & Developer Extensibility"],
    expectedOutcome: "Ship analytics features to customers using embeddable components and APIs",
    before: { label: "Embedded analytics setup", value: "Weeks of custom dev" },
    after: { label: "Embedded analytics setup", value: "Days with SDK/API" },
    scores: { wisdomai: 4, snowflake: 2, databricks: 2, powerbi: 4, sigma: 5, omni: 4, hex: 3, tableau: 4 },
    notes: {
      wisdomai: "API-first architecture with embeddable AI-powered analytics components.",
      snowflake: "No embedded analytics offering; data platform, not a BI tool.",
      databricks: "No embedded analytics; notebook-centric, not embeddable.",
      powerbi: "Power BI Embedded is mature; widely used for customer-facing analytics.",
      sigma: "Excellent embedded analytics offering — strong competitor for SaaS embedding.",
      omni: "Good embedding capabilities with clean API.",
      hex: "Basic embedding; not a primary use case for the platform.",
      tableau: "Tableau Embedded Analytics is mature and widely deployed.",
    },
  },
  {
    id: "uc-15",
    title: "Send automated reports to Slack every Monday with key changes highlighted",
    persona: "business-user",
    industries: ["tech", "retail", "financial"],
    challenge: "collaboration-gaps",
    outcomeCategory: "decision-velocity",
    keyMetric: "mtti",
    relatedProduct: "WisdomAI Workspaces",
    features: ["Slack / Teams Integration", "Scheduled Report Delivery", "AI-Generated Insights & Summaries"],
    expectedOutcome: "Teams start every week with AI-curated data highlights in their existing workflow",
    before: { label: "Report distribution", value: "Manual, inconsistent" },
    after: { label: "Report distribution", value: "Auto-delivered with AI narrative" },
    scores: { wisdomai: 5, snowflake: 2, databricks: 2, powerbi: 3, sigma: 4, omni: 3, hex: 3, tableau: 3 },
    notes: {
      wisdomai: "AI-generated narrative + charts delivered natively to Slack/Teams on schedule.",
      snowflake: "No native messaging integration or scheduled delivery.",
      databricks: "Notebook scheduling exists but no native Slack integration for reports.",
      powerbi: "Email-based scheduled delivery; Slack integration is basic.",
      sigma: "Good Slack integration for sharing; scheduled delivery available.",
      omni: "Basic notification integration; no rich Slack delivery.",
      hex: "Scheduled notebook runs can post to Slack; setup required.",
      tableau: "Scheduled subscriptions via email; Slack integration is basic.",
    },
  },
  {
    id: "uc-16",
    title: "Ensure every user only sees data they're authorized to access",
    persona: "cdo",
    industries: ["financial", "healthcare"],
    challenge: "compliance-risk",
    outcomeCategory: "trust-governance",
    keyMetric: "query-accuracy-adoption",
    relatedProduct: "WisdomAI Enterprise",
    features: ["Row-Level Security (RLS)", "SSO / SAML / SCIM", "Data Classification & Sensitivity"],
    expectedOutcome: "Fine-grained access control enforced automatically across all analytics surfaces",
    before: { label: "Access control coverage", value: "Inconsistent, manual" },
    after: { label: "Access control coverage", value: "100% enforced via RLS" },
    scores: { wisdomai: 4, snowflake: 5, databricks: 5, powerbi: 5, sigma: 4, omni: 3, hex: 3, tableau: 4 },
    notes: {
      wisdomai: "RLS enforced across AI queries, dashboards, and reports from the semantic layer.",
      snowflake: "Robust RLS with dynamic masking and governance policies.",
      databricks: "Unity Catalog provides row and column-level security.",
      powerbi: "Mature RLS integrated with Azure Active Directory.",
      sigma: "Team-based RLS with user attribute support.",
      omni: "Basic row-level security; enterprise features still developing.",
      hex: "Limited RLS; not a primary focus of the platform.",
      tableau: "Row-level security via Salesforce integration; mature access controls.",
    },
  },
  {
    id: "uc-17",
    title: "Build custom calculations without learning SQL or a formula language",
    persona: "business-user",
    industries: ["retail", "manufacturing", "healthcare"],
    challenge: "technical-barrier",
    outcomeCategory: "trust-governance",
    keyMetric: "query-accuracy-adoption",
    relatedProduct: "WisdomAI Explorer",
    features: ["Calculated Fields & Metrics", "No-Code Data Exploration", "Natural Language to SQL"],
    expectedOutcome: "Business users create custom metrics in natural language that are governed centrally",
    before: { label: "Custom metric creation", value: "Ticket to data team, days" },
    after: { label: "Custom metric creation", value: "Self-serve in minutes" },
    scores: { wisdomai: 5, snowflake: 1, databricks: 2, powerbi: 4, sigma: 5, omni: 4, hex: 3, tableau: 4 },
    notes: {
      wisdomai: "Describe the metric in plain English; AI generates and governs it automatically.",
      snowflake: "Requires SQL knowledge; no business-user metric creation interface.",
      databricks: "Notebook-based calculations; requires coding skills.",
      powerbi: "DAX formula builder is powerful but has a learning curve.",
      sigma: "Spreadsheet-style calculated fields are very intuitive for business users.",
      omni: "Good metric creation tools; requires some technical understanding.",
      hex: "Code-based calculations; not accessible for non-technical users.",
      tableau: "Calculated fields with UI builder; learning curve but powerful.",
    },
  },
  {
    id: "uc-18",
    title: "Connect real-time streaming data to dashboards without batch ETL delays",
    persona: "data-engineer",
    industries: ["tech", "financial", "manufacturing"],
    challenge: "data-silos",
    outcomeCategory: "decision-velocity",
    keyMetric: "mtti",
    relatedProduct: "WisdomAI Connect",
    features: ["Real-Time / Streaming Data", "Live Data / Direct Query"],
    expectedOutcome: "Dashboards reflect live operational data with sub-minute latency",
    before: { label: "Data freshness", value: "Hourly/daily batch refresh" },
    after: { label: "Data freshness", value: "Sub-minute streaming" },
    scores: { wisdomai: 4, snowflake: 3, databricks: 4, powerbi: 3, sigma: 3, omni: 3, hex: 3, tableau: 3 },
    notes: {
      wisdomai: "Native streaming support with live dashboard push; no batch dependency.",
      snowflake: "Snowpipe streaming is improving but dashboard latency still batch-like.",
      databricks: "Structured Streaming is strong; dashboard visualization is the gap.",
      powerbi: "Real-time streaming datasets exist but setup is complex and limited.",
      sigma: "Live queries to warehouse; streaming depends on warehouse capability.",
      omni: "Live queries but no native streaming data support.",
      hex: "No native streaming; relies on warehouse refresh cycles.",
      tableau: "Live connections supported; streaming depends on underlying source.",
    },
  },
  {
    id: "uc-19",
    title: "Scale analytics to 500+ concurrent users without performance degradation",
    persona: "cdo",
    industries: ["financial", "retail", "tech", "manufacturing"],
    challenge: "vendor-lock-in",
    outcomeCategory: "operational-efficiency",
    keyMetric: "etl-cost-analyst-leverage",
    relatedProduct: "WisdomAI Enterprise",
    features: ["Scalability & Performance", "On-Premises / Hybrid Deployment"],
    expectedOutcome: "Enterprise-grade performance at scale with flexible deployment options",
    before: { label: "Peak user handling", value: "Slowdowns above 100 users" },
    after: { label: "Peak user handling", value: "500+ concurrent, sub-second" },
    scores: { wisdomai: 4, snowflake: 5, databricks: 5, powerbi: 5, sigma: 4, omni: 3, hex: 3, tableau: 5 },
    notes: {
      wisdomai: "Cloud-native auto-scaling; hybrid deployment option for regulated industries.",
      snowflake: "Excellent scalability via compute isolation; proven at massive enterprise scale.",
      databricks: "Auto-scaling compute clusters; handles massive concurrency well.",
      powerbi: "Azure-backed scalability with Premium capacity; very mature.",
      sigma: "Good cloud scalability; growing enterprise deployment options.",
      omni: "Mid-market scale; enterprise performance features still developing.",
      hex: "Adequate for mid-size teams; not proven at large enterprise scale.",
      tableau: "Salesforce-backed enterprise scale; proven at massive deployments.",
    },
  },
  {
    id: "uc-20",
    title: "Write custom JS/D3 visualizations beyond built-in chart types",
    persona: "developer",
    industries: ["tech", "financial"],
    challenge: "dashboard-bottleneck",
    outcomeCategory: "operational-efficiency",
    keyMetric: "etl-cost-analyst-leverage",
    relatedProduct: "WisdomAI Dashboards",
    features: ["Custom / Coded Visualizations", "API & Developer Extensibility"],
    expectedOutcome: "Build pixel-perfect custom visualizations when standard charts aren't enough",
    before: { label: "Custom viz path", value: "Separate tool, manual data sync" },
    after: { label: "Custom viz path", value: "In-platform with live data" },
    scores: { wisdomai: 4, snowflake: 1, databricks: 4, powerbi: 4, sigma: 3, omni: 3, hex: 5, tableau: 4 },
    notes: {
      wisdomai: "Extensible visualization layer with JavaScript/D3 support alongside governed data.",
      snowflake: "No visualization capabilities; requires external tools entirely.",
      databricks: "Plotly, matplotlib, D3 all available within notebooks.",
      powerbi: "Custom visuals marketplace + R/Python visual support.",
      sigma: "Limited custom visualization; primarily built-in chart types.",
      omni: "Basic customization; no custom code visualizations.",
      hex: "Best-in-class custom viz: Plotly, Vega, D3, custom React components.",
      tableau: "Extensions API for custom viz; growing marketplace of custom components.",
    },
  },
];

